version: '3'

services:
  post:
    build: .
    depends_on:
      - 'database'
    ports:
      - '8000:8000'
  
  database:
    container_name: docker-local-mysql
    image: mysql:latest
    volumes:
      - "./data:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root